version: "3.2"

services:

  # This is just to make sure the volumes folder have right ownership for mm_app to work properly
  mm_prepare:
    image: alpine:3.7
    volumes:
      - ./volumes:/srv
    command: /bin/sh -c "mkdir -p /srv/app/mattermost/config && mkdir -p /srv/app/mattermost/data && mkdir -p /srv/app/mattermost/logs && touch /srv/app/mattermost/config/ready && chown -R 2000:2000 /srv/app"

  mm_db:
    container_name: mm_db
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    networks:
      mmnet:
        ipv4_address: 10.10.0.2

  mm_app:
    container_name: mm_app
    build:
      context: app
      args:
        - edition=team
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config
      - ./volumes/app/mattermost/data:/mattermost/data
      - ./volumes/app/mattermost/logs:/mattermost/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
    networks:
      mmnet:
        ipv4_address: 10.10.0.10

networks:
  mmnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
